first commit
made-ml-in-prod-2021/anirill pull request #1
Opened 2021-04-07 05:18 UTC by Anirill

Добрый день!
В readme.md написал (сразу почему-то не отображается, но если открыть файл оно там есть):
Клестов Андрей Владимирович 
https://data.mail.ru/profile/a.klestov/ 
Репозиторий для курса " Машинное обучение в продакшене".
Добавляю описание pull request я правильно понял, или что-то ещё нужно было написать?

2021-04-07 05:59 UTC, Mikhail-M requested changes
давайте что-нибудь напишем

2021-04-07 09:55 UTC, Mikhail-M commented
не вижу изменений в ревью, видимо это уже в мастере, да, давайте внесём какието изменения))
цель этого мини задания убедиться, что нет проблем с гитом, так что, плз

2021-04-07 13:13 UTC, Anirill commented
Переименовал файл, попробовал также расширение .py содержимое не отображается, хотя вроде бы должно.

2021-04-08 05:49 UTC, Mikhail-M commented
> Переименовал файл, попробовал также расширение .py содержимое не отображается, хотя вроде бы должно.

пробуйте еше, пригодится, что-то не так явно

2021-04-08 05:50 UTC, Mikhail-M commented
> > Переименовал файл, попробовал также расширение .py содержимое не отображается, хотя вроде бы должно.
> 
> пробуйте еше, пригодится, что-то не так явно

посмотрите в соседних репозиториях, как у коллег выглядит

2021-04-08 10:43 UTC, Anirill commented
Добавил аттрибуты, теперь вроде бы похоже, отображаются изменения, если зайти в коммит. Надеюсь, я тут не слишком сильно наспамил :(

2021-04-08 19:22 UTC, Mikhail-M commented
> Добавил аттрибуты, теперь вроде бы похоже, отображаются изменения, если зайти в коммит. Надеюсь, я тут не слишком сильно наспамил :(

Да ничего страшного))
можете squash commit сделать, чтобы в истории мастер ветки этих коммитов не было. 

Теперь похоже на правду

2021-04-08 19:23 UTC, Mikhail-M approved these changes

2021-04-08 21:00 UTC, merged